/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package application;

import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dai Phuc
 */
public class CoursePanel extends javax.swing.JInternalFrame {

    DefaultTableModel tableModel;
    List <Course> CourseList;
    List <Course> CourseList2;
    
    public CoursePanel() {
        
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        tableModel = (DefaultTableModel) tblCourse.getModel();
        showCourse();
        tblCourse.getColumnModel().getColumn(2).setPreferredWidth(20);
        tblCourse.getColumnModel().getColumn(3).setPreferredWidth(50);
        tblCourse.getColumnModel().getColumn(4).setPreferredWidth(50);
        tblCourse.getColumnModel().getColumn(5).setPreferredWidth(20);
    }
    
    public void placeholder(JTextField text){
        
        Font font = text.getFont();
        font = font.deriveFont(Font.ITALIC);
        text.setFont(font);
        text.setForeground(Color.gray);
        
    }
    
    public void placeholderRemove(JTextField text){
        
        Font font = SearchField.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        SearchField.setFont(font);
        SearchField.setForeground(Color.black);
        
    }
    
    public void showCourse(){
        
        CourseList = DAO.findAll();
                
        tableModel.setRowCount(0);
        
        CourseList.forEach(Course -> { 
            tableModel.addRow(new Object[] { Course.getCourseName(),
                Course.getTutor(), Course.getCredits(), Course.getClassCode(), Course.getCourseCode(), Course.getAmount()});
        });
        
    }
    
    public void showCourse2(){
        
        CourseList2 = DAO.findAllClass();
            
            tableModel.setRowCount(0);  
            
                CourseList2.forEach(Course -> { 
                    tableModel.addRow(new Object[] { Course.getCourseName(),
                    Course.getTutor(), Course.getCredits(), Course.getClassCode(), Course.getCourseCode(), Course.getAmount()});
                });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchButton = new javax.swing.JButton();
        SearchField = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        MyCourseCheck = new javax.swing.JCheckBox();
        RemoveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourse = new javax.swing.JTable();

        SearchButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        SearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/applicationIcon/search_16.png"))); // NOI18N
        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        SearchField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        SearchField.setText("Code/Name");
        SearchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchFieldFocusLost(evt);
            }
        });
        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });

        AddButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/applicationIcon/add-icon.png"))); // NOI18N
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        MyCourseCheck.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MyCourseCheck.setText("My Course Only");
        MyCourseCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyCourseCheckActionPerformed(evt);
            }
        });

        RemoveButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RemoveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/applicationIcon/remove-icon.png"))); // NOI18N
        RemoveButton.setText("Remove");
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        tblCourse.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tblCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Tutor", "Credits", "Class Code", "Course Code", "Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCourse.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblCourseAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCourseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCourse);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RemoveButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddButton)
                            .addComponent(SearchButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MyCourseCheck)
                            .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchButton)
                    .addComponent(SearchField))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton)
                    .addComponent(MyCourseCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(RemoveButton)
                .addGap(175, 175, 175))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        String searchString = SearchField.getText();
        tableModel.setRowCount(0);

        if (searchString.length()>0){

            if (DAO.search(searchString) == false){
                JOptionPane.showMessageDialog(this, "No course found!", "Error", JOptionPane.INFORMATION_MESSAGE);
                //                TextID.setBackground(new Color(255, 123, 123));
            } else {

                SearchField.setBackground(null);
                CourseList = DAO.findByFullName(searchString);

                CourseList.forEach(Course -> {
                    tableModel.addRow(new Object[] { Course.getCourseName(),
                        Course.getTutor(), Course.getCredits(), Course.getClassCode(), Course.getCourseCode(), Course.getAmount()});
            });

        }
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void SearchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFieldFocusGained
        // TODO add your handling code here:
        if (SearchField.getText().equals("Code/Name")){
            SearchField.setText(null);
            SearchField.requestFocus();
            placeholderRemove(SearchField);
        }
    }//GEN-LAST:event_SearchFieldFocusGained

    private void SearchFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFieldFocusLost
        // TODO add your handling code here:
        if (SearchField.getText().length()==0){

            placeholder(SearchField);
            SearchField.setText("Code/Name");

        }
    }//GEN-LAST:event_SearchFieldFocusLost

    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchFieldActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        if (DAO.check(Application.ID)){
            JOptionPane.showMessageDialog(this, "You have already signed in this class!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            DAO.add();
            JOptionPane.showMessageDialog(this, "Succesfully asigned!", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        showCourse();
    }//GEN-LAST:event_AddButtonActionPerformed

    private void MyCourseCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyCourseCheckActionPerformed
        // TODO add your handling code here:
        if (MyCourseCheck.isSelected()){

            DefaultTableModel model = (DefaultTableModel) tblCourse.getModel();
            while(model.getRowCount() > 0)
            {
                model.removeRow(0);
            }

            showCourse2();

        } else {
            showCourse();
        }
    }//GEN-LAST:event_MyCourseCheckActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        // TODO add your handling code here:
        if (!DAO.check(Application.ID)){
            JOptionPane.showMessageDialog(this, "You are not in this class!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            DAO.remove();
            JOptionPane.showMessageDialog(this, "Succesfully removed!", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        showCourse();
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void tblCourseAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblCourseAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCourseAncestorAdded

    private void tblCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCourseMouseClicked
        // TODO add your handling code here:
        JTable source = (JTable)evt.getSource();
        int row = source.rowAtPoint( evt.getPoint() );

        Application.courseCode = source.getModel().getValueAt(row, 4)+"";
        Application.classCode = source.getModel().getValueAt(row, 3)+"";
    }//GEN-LAST:event_tblCourseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JCheckBox MyCourseCheck;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCourse;
    // End of variables declaration//GEN-END:variables
}
