/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Dai Phuc
 */
public class CreateExamFrame extends javax.swing.JFrame {

    Color DefaultColor, ClickedColor;

    public CreateExamFrame() {

        DefaultColor = new Color(11, 34, 50);
        ClickedColor = new Color(251, 154, 59);

        initComponents();

        this.setLocationRelativeTo(null);
        CreateExamButton.setBackground(DefaultColor);
        RandomExamButton.setBackground(DefaultColor);
        FinishButton.setBackground(DefaultColor);
        DeleteButton.setBackground(DefaultColor);
        
        DAO.findCourseName(Application.ExamID);

        NameTestField.setText(Application.ExamNameTest);
        SubjectField.setText(Application.ExamCourseName);
        ClassCodeField.setText(Application.ExamClassCode);

        System.out.println(Application.ExamCourseName + " " + Application.ExamClassCode + Application.ExamNameTest);
    }

    public void CloseFrame() {
        super.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        NameTestField = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SubjectField = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ClassCodeField = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        RandomExamButton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CreateExamButton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FinishButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        DeleteButton = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TypeButton = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        MainTab = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(971, 461));

        jPanel1.setBackground(new java.awt.Color(251, 154, 59));

        jLabel6.setBackground(new java.awt.Color(51, 204, 0));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setText("Name:");

        NameTestField.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        NameTestField.setText("jLabel3");

        jLabel8.setBackground(new java.awt.Color(51, 204, 0));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 0));
        jLabel8.setText("Subject:");

        SubjectField.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        SubjectField.setText("jLabel3");

        jLabel9.setBackground(new java.awt.Color(51, 204, 0));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 0));
        jLabel9.setText("Class Code: ");

        ClassCodeField.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ClassCodeField.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameTestField)
                .addGap(36, 36, 36)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubjectField)
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClassCodeField)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ClassCodeField))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SubjectField)
                        .addComponent(NameTestField)))
                .addGap(20, 20, 20))
        );

        jPanel3.setBackground(new java.awt.Color(11, 34, 50));

        RandomExamButton.setBackground(new java.awt.Color(11, 34, 50));
        RandomExamButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RandomExamButtonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RandomExamButtonMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Random Exam");

        javax.swing.GroupLayout RandomExamButtonLayout = new javax.swing.GroupLayout(RandomExamButton);
        RandomExamButton.setLayout(RandomExamButtonLayout);
        RandomExamButtonLayout.setHorizontalGroup(
            RandomExamButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RandomExamButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RandomExamButtonLayout.setVerticalGroup(
            RandomExamButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RandomExamButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CreateExamButton.setBackground(new java.awt.Color(11, 34, 50));
        CreateExamButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateExamButtonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CreateExamButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CreateExamButtonMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/applicationIcon/home-icon.png"))); // NOI18N
        jLabel1.setText("Create Exam");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CreateExamButtonLayout = new javax.swing.GroupLayout(CreateExamButton);
        CreateExamButton.setLayout(CreateExamButtonLayout);
        CreateExamButtonLayout.setHorizontalGroup(
            CreateExamButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateExamButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        CreateExamButtonLayout.setVerticalGroup(
            CreateExamButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateExamButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        FinishButton.setBackground(new java.awt.Color(11, 34, 50));
        FinishButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FinishButtonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FinishButtonMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Finish");

        javax.swing.GroupLayout FinishButtonLayout = new javax.swing.GroupLayout(FinishButton);
        FinishButton.setLayout(FinishButtonLayout);
        FinishButtonLayout.setHorizontalGroup(
            FinishButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinishButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FinishButtonLayout.setVerticalGroup(
            FinishButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FinishButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        DeleteButton.setBackground(new java.awt.Color(11, 34, 50));
        DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DeleteButtonMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Delete");

        javax.swing.GroupLayout DeleteButtonLayout = new javax.swing.GroupLayout(DeleteButton);
        DeleteButton.setLayout(DeleteButtonLayout);
        DeleteButtonLayout.setHorizontalGroup(
            DeleteButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DeleteButtonLayout.setVerticalGroup(
            DeleteButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TypeButton.setBackground(new java.awt.Color(11, 34, 50));
        TypeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TypeButtonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TypeButtonMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Activate Type");

        javax.swing.GroupLayout TypeButtonLayout = new javax.swing.GroupLayout(TypeButton);
        TypeButton.setLayout(TypeButtonLayout);
        TypeButtonLayout.setHorizontalGroup(
            TypeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TypeButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TypeButtonLayout.setVerticalGroup(
            TypeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TypeButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(RandomExamButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FinishButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CreateExamButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(TypeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(CreateExamButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RandomExamButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FinishButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TypeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainTabLayout = new javax.swing.GroupLayout(MainTab);
        MainTab.setLayout(MainTabLayout);
        MainTabLayout.setHorizontalGroup(
            MainTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );
        MainTabLayout.setVerticalGroup(
            MainTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainTab)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(MainTab)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RandomExamButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RandomExamButtonMousePressed
        // TODO add your handling code here:
        CreateExamButton.setBackground(DefaultColor);
        RandomExamButton.setBackground(ClickedColor);
        TypeButton.setBackground(DefaultColor);
        FinishButton.setBackground(DefaultColor);
        DeleteButton.setBackground(DefaultColor);
    }//GEN-LAST:event_RandomExamButtonMousePressed

    private void CreateExamButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateExamButtonMouseClicked
        // TODO add your handling code here:
        DAO.eraseQuestion(Application.ExamID);
        CreateExamPanel CreateExamTab = new CreateExamPanel();
        MainTab.removeAll();
        MainTab.add(CreateExamTab).setVisible(true);
    }//GEN-LAST:event_CreateExamButtonMouseClicked

    private void CreateExamButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateExamButtonMousePressed
        // TODO add your handling code here:

        //        if (CourseTab == null){
        //            CourseTab=new CoursePanel();
        //            MainTab.addTab("Search", CourseTab);
        //        }
        //        //        CoursePanel.showProduct();
        //        MainTab.setSelectedComponent(CourseTab);
        CreateExamButton.setBackground(ClickedColor);
        RandomExamButton.setBackground(DefaultColor);
        FinishButton.setBackground(DefaultColor);
        DeleteButton.setBackground(DefaultColor);
        TypeButton.setBackground(DefaultColor);

    }//GEN-LAST:event_CreateExamButtonMousePressed

    private void FinishButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinishButtonMousePressed
        // TODO add your handling code here:
        CreateExamButton.setBackground(DefaultColor);
        RandomExamButton.setBackground(DefaultColor);
        FinishButton.setBackground(ClickedColor);
        DeleteButton.setBackground(DefaultColor);
        TypeButton.setBackground(DefaultColor);
    }//GEN-LAST:event_FinishButtonMousePressed

    private void DeleteButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMousePressed
        // TODO add your handling code here:
        CreateExamButton.setBackground(DefaultColor);
        RandomExamButton.setBackground(DefaultColor);
        FinishButton.setBackground(DefaultColor);
        TypeButton.setBackground(DefaultColor);
        DeleteButton.setBackground(ClickedColor);

    }//GEN-LAST:event_DeleteButtonMousePressed

    private void FinishButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinishButtonMouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Do you want to finish?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            this.CloseFrame();
        }
    }//GEN-LAST:event_FinishButtonMouseClicked

    private void DeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseClicked
        // TODO add your handling code here:        
        int response = JOptionPane.showConfirmDialog(this, "Do you want delete this exam?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            DAO.deleteExam(Application.ExamID);
            this.CloseFrame();
        }
    }//GEN-LAST:event_DeleteButtonMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        CreateExamPanel CreateExamTab = new CreateExamPanel();
        MainTab.removeAll();
        MainTab.add(CreateExamTab).setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void CreateExamButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateExamButtonMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateExamButtonMouseReleased

    private void RandomExamButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RandomExamButtonMouseClicked
        // TODO add your handling code here:
        DAO.eraseQuestion(Application.ExamID);
        RandomExamPanel CreateRandomExamTab = new RandomExamPanel();
        MainTab.removeAll();
        MainTab.add(CreateRandomExamTab).setVisible(true);
    }//GEN-LAST:event_RandomExamButtonMouseClicked

    private void TypeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TypeButtonMouseClicked
        // TODO add your handling code here:
        new TypeFrame().setVisible(true);
    }//GEN-LAST:event_TypeButtonMouseClicked

    private void TypeButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TypeButtonMousePressed
        // TODO add your handling code here:
        CreateExamButton.setBackground(DefaultColor);
        RandomExamButton.setBackground(DefaultColor);
        TypeButton.setBackground(ClickedColor);
        FinishButton.setBackground(DefaultColor);
        DeleteButton.setBackground(DefaultColor);
    }//GEN-LAST:event_TypeButtonMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateExamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateExamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateExamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateExamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateExamFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClassCodeField;
    private javax.swing.JPanel CreateExamButton;
    private javax.swing.JPanel DeleteButton;
    private javax.swing.JPanel FinishButton;
    private javax.swing.JDesktopPane MainTab;
    private javax.swing.JLabel NameTestField;
    private javax.swing.JPanel RandomExamButton;
    private javax.swing.JLabel SubjectField;
    private javax.swing.JPanel TypeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
