/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dai Phuc
 */
public class ExamFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterFrame
     */
    String filename = null;
    String id = new String();
    byte[] person_image = null;
    String activate = new String();

    Icon correctIcon = new ImageIcon("correct.png");

    Object[][] data
            = {
                {correctIcon, "About"},};
    
    String[] columnNames = {};

    DefaultTableModel tableModel = new DefaultTableModel(data, columnNames) {
        public Class getColumnClass(int column)
            {
                return getValueAt(0, column).getClass();
            }
    };

    List<Exam> ExamList;

    public ExamFrame() {
        initComponents();
        System.out.println(Application.ID);
        setLocationRelativeTo(null);
        tableModel = (DefaultTableModel) tblExam.getModel();
        showExam();
    }

    public void showExam() {

        ExamList = DAO.findExam(Application.ID);

        tableModel.setRowCount(0);

        ExamList.forEach(Exam -> {
            tableModel.addRow(new Object[]{Exam.getCourseName(),
                Exam.getNameTest(), Exam.getClassCode(), Exam.getActivate(), Exam.getTime(), Exam.getDate(), Exam.getID()});
        });
    }

    public void CloseFrame() {
        super.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new keeptoo.KGradientPanel();
        ActivateButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExam = new javax.swing.JTable();
        FinishButton = new javax.swing.JButton();
        DeactivateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        ActivateButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ActivateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/applicationIcon/available-icon.png"))); // NOI18N
        ActivateButton.setText("Activate");
        ActivateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActivateButtonActionPerformed(evt);
            }
        });

        tblExam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Subject", "Name", "Class Code", "Activate", "Time", "Date", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblExam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblExamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblExam);
        if (tblExam.getColumnModel().getColumnCount() > 0) {
            tblExam.getColumnModel().getColumn(0).setResizable(false);
            tblExam.getColumnModel().getColumn(1).setResizable(false);
            tblExam.getColumnModel().getColumn(2).setResizable(false);
            tblExam.getColumnModel().getColumn(3).setResizable(false);
            tblExam.getColumnModel().getColumn(4).setResizable(false);
            tblExam.getColumnModel().getColumn(5).setResizable(false);
            tblExam.getColumnModel().getColumn(6).setResizable(false);
        }

        FinishButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        FinishButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/applicationIcon/logout (1).png"))); // NOI18N
        FinishButton.setText("Finish");
        FinishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishButtonActionPerformed(evt);
            }
        });

        DeactivateButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        DeactivateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/applicationIcon/remove-icon.png"))); // NOI18N
        DeactivateButton.setText("Deactivate");
        DeactivateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeactivateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE))
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(ActivateButton)
                        .addGap(125, 125, 125)
                        .addComponent(DeactivateButton)
                        .addGap(129, 129, 129)
                        .addComponent(FinishButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ActivateButton)
                    .addComponent(DeactivateButton)
                    .addComponent(FinishButton))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActivateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActivateButtonActionPerformed
        // TODO add your handling code here:
        if (!activate.equals("0")) {
            Connection conn = null;
            PreparedStatement statement = null;

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/online?allowPublicKeyRetrieval=true&user=root&useSSL=false&password=daiphucprohehe");
                PreparedStatement passnew = conn.prepareStatement("update exam set activate = 1 where id = ?",
                        ResultSet.CONCUR_UPDATABLE);
                passnew.setString(1, id);
                passnew.executeUpdate();

            } catch (Exception e) {
                e.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "Successfully activate exam!", "Alert", JOptionPane.INFORMATION_MESSAGE);
            showExam();
        } else if (activate.equals("0")) {
            JOptionPane.showMessageDialog(this, "Cannot activate this exam!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_ActivateButtonActionPerformed

    private void FinishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishButtonActionPerformed
        // TODO add your handling code here:
        CloseFrame();
    }//GEN-LAST:event_FinishButtonActionPerformed

    private void tblExamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblExamMouseClicked
        // TODO add your handling code here:
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());

        id = source.getModel().getValueAt(row, 6) + "";
        activate = source.getModel().getValueAt(row, 3) + "";
    }//GEN-LAST:event_tblExamMouseClicked

    private void DeactivateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeactivateButtonActionPerformed
        // TODO add your handling code here:
        if (activate.equals("1")) {
            Connection conn = null;
            PreparedStatement statement = null;

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/online?allowPublicKeyRetrieval=true&user=root&useSSL=false&password=daiphucprohehe");
                PreparedStatement passnew = conn.prepareStatement("update exam set activate = 2 where id = ?",
                        ResultSet.CONCUR_UPDATABLE);
                passnew.setString(1, id);
                passnew.executeUpdate();

            } catch (Exception e) {
                e.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "Successfully deactivate exam!", "Alert", JOptionPane.INFORMATION_MESSAGE);
            showExam();
        } else {
            JOptionPane.showMessageDialog(this, "Cannot deactivate this exam!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DeactivateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActivateButton;
    private javax.swing.JButton DeactivateButton;
    private javax.swing.JButton FinishButton;
    private keeptoo.KGradientPanel contentPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblExam;
    // End of variables declaration//GEN-END:variables
}
