/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package application;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dai Phuc
 */
public class ExamTutorPanel extends javax.swing.JInternalFrame {

    String CourseCode = new String();
    String CourseName = new String();
    String ClassCode = new String();
    String Tutor = Application.userName;
    int Length = 0;

    DefaultTableModel tableModel;
    List<Course> CourseList;

    public ExamTutorPanel() {

        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();

//        DateField.setDate(dtf.format(now));
        initComponents();
        tableModel = (DefaultTableModel) tblCourse.getModel();
        showCourse();
    }

    public void showCourse() {

        CourseList = DAO.findTutorClass(Application.userName);

        tableModel.setRowCount(0);

        CourseList.forEach(Course -> {
            tableModel.addRow(new Object[]{Course.getCourseName(),
                Course.getTutor(), Course.getCredits(), Course.getClassCode(), Course.getCourseCode(), Course.getAmount()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TimeField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        IDField = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ModifyButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourse = new javax.swing.JTable();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Time");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("ID");

        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });

        IDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDFieldActionPerformed(evt);
            }
        });

        AddButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/applicationIcon/add-icon.png"))); // NOI18N
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/applicationIcon/show.png"))); // NOI18N
        jButton2.setText("Show My  Exam");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ModifyButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ModifyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/applicationIcon/draw.png"))); // NOI18N
        ModifyButton.setText("Modify");
        ModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyButtonActionPerformed(evt);
            }
        });

        tblCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Tutor", "Credits", "Class Code", "Course Code", "Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCourseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCourse);
        if (tblCourse.getColumnModel().getColumnCount() > 0) {
            tblCourse.getColumnModel().getColumn(0).setResizable(false);
            tblCourse.getColumnModel().getColumn(1).setResizable(false);
            tblCourse.getColumnModel().getColumn(2).setResizable(false);
            tblCourse.getColumnModel().getColumn(3).setResizable(false);
            tblCourse.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddButton)
                                .addGap(18, 18, 18)
                                .addComponent(ModifyButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton)
                    .addComponent(ModifyButton))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        String ID = IDField.getText();
        String NameTest = NameField.getText();
        String Time = TimeField.getText();
        Application.ExamID = IDField.getText();
        Application.ExamNameTest = NameField.getText();

        DAO.findCourseName(ID);

        try {
            if (TimeField.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Time is null!", "Error", JOptionPane.ERROR_MESSAGE);
                TimeField.setBackground(new Color(255, 123, 123));
            } else if (NameField.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "ID is null!", "Error", JOptionPane.ERROR_MESSAGE);
                NameField.setBackground(new Color(255, 123, 123));
            } else if (IDField.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Origin Price is null!", "Error", JOptionPane.ERROR_MESSAGE);
                IDField.setBackground(new Color(255, 123, 123));
            } else if (Application.ExamCourseCode.equals("")) {
                JOptionPane.showMessageDialog(this, "Please select your class!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                Exam exm = new Exam();
                TimeField.setBackground(null);
                NameField.setBackground(null);
                IDField.setBackground(null);

                exm.setTime("");
                exm.setNameTest(NameTest);
                exm.setID(ID);
                exm.setLength(Integer.parseInt(Time));
                exm.setCourseName(CourseName);
                exm.setCourseCode(CourseCode);
                exm.setClassCode(ClassCode);
                exm.setTutor(Tutor);

                if (DAO.check(ID, 2) == true) {
                    JOptionPane.showMessageDialog(this, "ID has already existed!", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    DAO.insertExam(exm);
                    JOptionPane.showMessageDialog(this, "Successfully added exam!", "Alert", JOptionPane.INFORMATION_MESSAGE);
                    new CreateExamFrame().setVisible(true);
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Errol: " + e.getMessage());
            e.printStackTrace();
        }
        showCourse();
    }//GEN-LAST:event_AddButtonActionPerformed

    private void ModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyButtonActionPerformed
        // TODO add your handling code here:
        String ID = IDField.getText();

        if (DAO.check(ID, 2) == false) {
            JOptionPane.showMessageDialog(this, "ID is not existed!", "Error", JOptionPane.ERROR_MESSAGE);
            IDField.setBackground(new Color(255, 123, 123));
        } else {
            String time = TimeField.getText();
            if (!time.equals("")) {
                Connection conn = null;
                PreparedStatement statement = null;
                try {

                    Class.forName("com.mysql.cj.jdbc.Driver");
                    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/online?user=root&useSSL=false&password=daiphucprohehe");
                    PreparedStatement passnew = conn.prepareStatement("update exam set length = ? where id = ?", ResultSet.TYPE_SCROLL_SENSITIVE,
                            ResultSet.CONCUR_UPDATABLE);
                    
                    passnew.setString(1, time);
                    passnew.setString(2, ID);
                    
                    int rs = passnew.executeUpdate();


                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            IDField.setBackground(null);
            DAO.findCourseName(ID);
            Application.ExamID = ID;
            new CreateExamFrame().setVisible(true);
            System.out.println(Application.ExamID);
        }
        showCourse();
    }//GEN-LAST:event_ModifyButtonActionPerformed

    private void tblCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCourseMouseClicked
        // TODO add your handling code here:
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
//        DAO.findCourseName();

        CourseCode = source.getModel().getValueAt(row, 4) + "";
        ClassCode = source.getModel().getValueAt(row, 3) + "";
        CourseName = source.getModel().getValueAt(row, 0) + "";

        Application.ExamClassCode = source.getModel().getValueAt(row, 3) + "";
        Application.ExamCourseCode = source.getModel().getValueAt(row, 4) + "";

        Connection conn = null;
        PreparedStatement statement = null;

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/online?user=root&useSSL=false&password=daiphucprohehe");
            PreparedStatement passnew = conn.prepareStatement("select * from exam where courseCode = ?", ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);

            passnew.setString(1, Application.ExamCourseCode);
            ResultSet rs = passnew.executeQuery();

            if (rs.next()) {
                Application.ExamCourseName = rs.getString("courseName");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_tblCourseMouseClicked

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void IDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new ExamFrame().setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField IDField;
    private javax.swing.JButton ModifyButton;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextField TimeField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCourse;
    // End of variables declaration//GEN-END:variables
}
