/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Dai Phuc
 */
public class LoadingFrame extends javax.swing.JFrame {

    
    public LoadingFrame() {
        
//        UIManager.put("ProgressBar.background", Color.GREEN);
//        UIManager.put("ProgressBar.foreground", Color.GREEN);
//        UIManager.put("ProgressBar.selectionBackground", Color.GREEN);
//        UIManager.put("ProgressBar.selectionForeground", Color.GREEN);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();
        LoadingLabel = new javax.swing.JLabel();
        LoadingNumber = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setPreferredSize(new java.awt.Dimension(700, 400));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel1.setText("ONLINE STUDYING APPLICATION");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, 30));

        LoadingBar.setForeground(Color.red);
        LoadingBar.setBackground(new java.awt.Color(255, 102, 102));
        LoadingBar.setForeground(new java.awt.Color(255, 0, 0));
        kGradientPanel1.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 580, 20));

        LoadingLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LoadingLabel.setText("Loading ...");
        kGradientPanel1.add(LoadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        LoadingNumber.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LoadingNumber.setText("0%");
        kGradientPanel1.add(LoadingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 50, 30));

        jLabel2.setText("_______________________________________________________________________________________________________________________");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 410, 27));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 271, 89, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("Phan Ba Dai Phuc");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 150, 20));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("Truong Quoc Dinh");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 150, 20));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setText("Tutor:");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 50, 20));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText("Student:");
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 70, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info: javax.swing.UIManager.getInstalledLookAndFeels()){
                if ("Nimbus".equals(info.getName())){
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(LoadingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null ,ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex){
            java.util.logging.Logger.getLogger(LoadingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex){
            java.util.logging.Logger.getLogger(LoadingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        LoadingFrame lf = new LoadingFrame();
        lf.setVisible(true);
        
        try{
            
            for (int i=0;i<=100;i++){
                
                Thread.sleep(25);
                lf.LoadingNumber.setText(i+"%");
                
                if (i == 10){
                    lf.LoadingLabel.setText("Turning on Modules...");
                }
                
                if (i == 20){
                    lf.LoadingLabel.setText("Loading Modules...");
                }
                
                if (i == 50){
                    lf.LoadingLabel.setText("Connecting to Database...");
                }
                
                if (i == 70){
                    lf.LoadingLabel.setText("Connection Successful!");
                }
                
                if (i == 90){
                    lf.LoadingLabel.setText("Launching Application");
                }
                
                lf.LoadingBar.setValue(i);
            }
         
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                lf.dispose();
                lf.setVisible(false);
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingLabel;
    private javax.swing.JLabel LoadingNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
