/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package application;

import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
//import org.apache.commons.lang.math.NumberUtils;

/**
 *
 * @author Dai Phuc
 */
public class RandomExamPanel extends javax.swing.JInternalFrame {

    public int ThreeMark = 0;
    public int FourMark = 0;
    public int FiveMark = 0;
    public int TotalQuestion = 0;
    
    DefaultTableModel tableModel;
    List<Question> QuestionList;

    public RandomExamPanel() {

        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);

        initComponents();
        tableModel = (DefaultTableModel) tblQuestions.getModel();
        
        tblQuestions.getColumnModel().getColumn(0).setPreferredWidth(400);
        tblQuestions.getColumnModel().getColumn(1).setPreferredWidth(80);
        tblQuestions.getColumnModel().getColumn(2).setPreferredWidth(80);

        Mark3Total.setText("/" + String.valueOf(DAO.totalQuesiton("3")));
        Mark4Total.setText("/" + String.valueOf(DAO.totalQuesiton("4")));
        Mark5Total.setText("/" + String.valueOf(DAO.totalQuesiton("5")));
        
    }
    
    public void showQuestion() {

        QuestionList = DAO.findRandomQuestion(Integer.parseInt(Mark3.getText()), Integer.parseInt(Mark4.getText()), Integer.parseInt(Mark5.getText()));

        tableModel.setRowCount(0);

        QuestionList.forEach(Question -> {
            tableModel.addRow(new Object[]{
                Question.getQuestions(), Question.getId(), Question.getGrade()});
        });
    }

    public static boolean isNumeric(String strNum) {
        if (strNum == null) {
            return false;
        }
        try {
            double d = Double.parseDouble(strNum);
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TotalMarkField = new javax.swing.JLabel();
        NumberQuestionField = new javax.swing.JLabel();
        Mark3 = new javax.swing.JTextField();
        Mark4 = new javax.swing.JTextField();
        Mark5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuestions = new javax.swing.JTable();
        ImplementButton = new javax.swing.JButton();
        Mark5Total = new javax.swing.JLabel();
        Mark3Total = new javax.swing.JLabel();
        Mark4Total = new javax.swing.JLabel();
        Warn3 = new javax.swing.JLabel();
        Warn4 = new javax.swing.JLabel();
        Warn5 = new javax.swing.JLabel();
        ClearButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(780, 392));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Total Marks:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mark 3:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mark 4:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Mark 5:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Number of Question(s):");

        TotalMarkField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TotalMarkField.setText("0");

        NumberQuestionField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NumberQuestionField.setText("0");

        Mark3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Mark3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mark3ActionPerformed(evt);
            }
        });

        Mark4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Mark4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mark4ActionPerformed(evt);
            }
        });

        Mark5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tblQuestions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Questions", "ID", "Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblQuestions.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblQuestions);
        if (tblQuestions.getColumnModel().getColumnCount() > 0) {
            tblQuestions.getColumnModel().getColumn(0).setResizable(false);
        }

        ImplementButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ImplementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/applicationIcon/available-icon.png"))); // NOI18N
        ImplementButton.setText("Implement");
        ImplementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImplementButtonActionPerformed(evt);
            }
        });

        Mark5Total.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Mark5Total.setText("jLabel1");

        Mark3Total.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Mark3Total.setText("jLabel1");

        Mark4Total.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Mark4Total.setText("jLabel1");

        Warn3.setForeground(new java.awt.Color(255, 0, 0));

        Warn4.setForeground(new java.awt.Color(255, 0, 0));

        Warn5.setForeground(new java.awt.Color(255, 0, 0));

        ClearButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ClearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/applicationIcon/cleaning.png"))); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(9, 9, 9)
                                .addComponent(Mark5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(9, 9, 9)
                                .addComponent(Mark3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(9, 9, 9)
                                .addComponent(Mark4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Mark5Total)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Warn5, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Mark4Total)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Warn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Mark3Total)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Warn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ImplementButton)
                                .addGap(52, 52, 52)
                                .addComponent(ClearButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(14, 14, 14)
                                    .addComponent(NumberQuestionField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(jLabel2)
                                    .addGap(17, 17, 17)
                                    .addComponent(TotalMarkField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(NumberQuestionField))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Mark3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Mark3Total)
                        .addComponent(Warn3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Mark4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mark4Total)
                    .addComponent(Warn4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Mark5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mark5Total)
                    .addComponent(Warn5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(TotalMarkField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImplementButton)
                    .addComponent(ClearButton))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Mark4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mark4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mark4ActionPerformed

    private void Mark3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mark3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mark3ActionPerformed

    private void ImplementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImplementButtonActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(Mark3.getText());
        int b = Integer.parseInt(Mark4.getText());
        int c = Integer.parseInt(Mark5.getText());
        
        boolean res3 = false;
        boolean res4 = false;
        boolean res5 = false;

        if (a > DAO.totalQuesiton("3")) {
//            JOptionPane.showMessageDialog(this, "Not enough question for 3 marks!", "Error", JOptionPane.ERROR_MESSAGE);
            Mark3.setBackground(new Color(255, 123, 123));
            Warn3.setText("Not enough questions!");
        } else {
            Mark3.setBackground(new Color(255, 255, 255));
            Warn3.setText("");
            res3 = true;
        }
        if (b > DAO.totalQuesiton("4")) {
//            JOptionPane.showMessageDialog(this, "Not enough question for 4 marks!", "Error", JOptionPane.ERROR_MESSAGE);
            Mark4.setBackground(new Color(255, 123, 123));
            Warn4.setText("Not enough questions!");
        } else {
            Mark4.setBackground(new Color(255, 255, 255));
            Warn4.setText("");
            res4 = true;
        }
        if (c > DAO.totalQuesiton("5")) {
//            JOptionPane.showMessageDialog(this, "Not enough question for 5 marks!", "Error", JOptionPane.ERROR_MESSAGE);
            Mark5.setBackground(new Color(255, 123, 123));
            Warn5.setText("Not enough questions!");
        } else {
            Mark5.setBackground(new Color(255, 255, 255));
            Warn5.setText("");
            res5 = true;
        }
        if (res3 == true && res4 == true && res5 == true) {
                int total = Integer.parseInt(Mark3.getText()) + Integer.parseInt(Mark4.getText()) + Integer.parseInt(Mark5.getText());
                int mark = Integer.parseInt(Mark3.getText()) * 3 + Integer.parseInt(Mark4.getText()) * 4 + Integer.parseInt(Mark5.getText()) * 5;
                NumberQuestionField.setText(String.valueOf(total));
                TotalMarkField.setText(String.valueOf(mark));
                DAO.eraseQuestion(Application.ExamID);
                showQuestion();
        }
    }//GEN-LAST:event_ImplementButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton ImplementButton;
    private javax.swing.JTextField Mark3;
    private javax.swing.JLabel Mark3Total;
    private javax.swing.JTextField Mark4;
    private javax.swing.JLabel Mark4Total;
    private javax.swing.JTextField Mark5;
    private javax.swing.JLabel Mark5Total;
    private javax.swing.JLabel NumberQuestionField;
    private javax.swing.JLabel TotalMarkField;
    private javax.swing.JLabel Warn3;
    private javax.swing.JLabel Warn4;
    private javax.swing.JLabel Warn5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblQuestions;
    // End of variables declaration//GEN-END:variables
}
